mod "boxen",    "0.1.8",  :github_tarball => "boxen/puppet-boxen"
mod "homebrew", "0.0.17", :github_tarball => "boxen/puppet-homebrew"
mod "stdlib",   "3.0.0",  :github_tarball => "puppetlabs/puppetlabs-stdlib"
